### ISSUE TITLE
face_restore_visability & Codeformer_weight is missing - 0.4.1 BETA8

### ISSUE THREAD

**Issue by lord-lethris** [Gourieff/comfyui-reactor-node#208]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

basically I wrote a workflow, then shared it, and a number of people are saying it is broke.  I checked the nodes and I spotted that the ReActor Node was completely different.  So I downloaded the latest version of ReActor (0.4.1 BETA8), removed and re-installed the node.  installed requirements.  then in my workflow, I removed and re-added the node.  but those options:

> face_restore_visability
> Codeformer_weight 

Are missing.  Where as everyone else can seem to see them.

`[ReActor] - STATUS - Running v0.4.1-b8 in ComfyUI`

### Steps to reproduce the problem

Open ComfyUI
Clear Workflow
Add ReActor Node.

face_restore_visability & Codeformer_weight is missing 

### Sysinfo

> OS - Windows 11
> Python - 3.10.11
> CPU - AMD Ryzen 9 5900X 12-Core Processor running at 6 Cores
> GPU - AMD Radeon RX 6800

No other nodes in Workflow as I cleared the workflow however here is my list of loaded nodes:

> imageflip_ally.py
> gaussian_blur_ally.py
> histogram_equalization.py
> saturation_ally.py
> clip_text_encode_split.py
> SDXLAspectRatio.py
> fcSuite.py
> Pseudo_HDR_ally.py
> CLIPTextFromTemplateEncode.py
> ComfyUI_ADV_CLIP_emb
> DeepCash.py
> ComfyUI_TiledKSampler
> ComfyUI_SimpleMath
> comfyui-optical-flow
> rembg-comfyui-node
> sharpness_ally.py
> sdxl_prompt_styler
> Mile_High_Styler
> ksampler_sdxl.py
> ControlNet-LLLite-ComfyUI
> LoadLoraWithTags
> ComfyUI_toyxyz_test_nodes
> ComfyUI_Cutoff
> ComfyUI-post-processing-nodes
> ComfyUI_JPS-Nodes
> ComfyUi-NoodleWebcam
> ComfyUI_Noise
> SD-Advanced-Noise
> ComfyUI_ResolutionSelector
> conditioning_sizing_for_SDXL.py
> brightness_contrast_ally.py
> ComfyUI-Styles_CSV_Loader
> ComfyUI_NestedNodeBuilder
> comfy-plasma
> ComfyUI_experiments
> ComfyUI-TGu-utils
> ComfyQR-scanning-nodes
> ComfyQR
> comfy-nodes
> comfyui-portrait-master
> ComfyUI_IPAdapter_plus
> images-grid-comfy-plugin
> ComfyUI-WD14-Tagger
> comfy_clip_blip_node
> ComfyUI_Dave_CustomNode
> QualityOfLifeSuit_Omar92
> ComfyMath
> ComfyUI_Load_Image_With_Metadata
> ComfyUI_UltimateSDUpscale
> failfast-comfyui-extensions
> comfyui-animatediff
> Derfuu_ComfyUI_ModdedNodes
> ComfyUI_FizzNodes
> ComfyUI-Custom-Scripts
> rgthree-comfy
> ComfyUI-Advanced-ControlNet
> efficiency-nodes-comfyui
> ComfyUI-AnimateDiff-Evolved
> facerestore_cf
> comfyui-prompt-reader-node
> comfyui-prompt-control
> ComfyUI_Comfyroll_CustomNodes
> comfyui-reactor-node.disable
> ComfyUI-Marigold
> ComfyUI_tinyterraNodes
> sdxl_prompt_styler-main
> comfyui-dynamicprompts
> ComfyUI-Manager
> ComfyUI-Inspire-Pack
> comfyui-reactor-node
> ComfyUI-FaceSwap
> ComfyUI_Custom_Nodes_AlekPet
> comfyui_controlnet_aux
> ComfyUI-Allor
> SeargeSDXL
> abg-comfyui
> ComfyUI-VideoHelperSuite
> comfy_mtb
> ComfyUI-Portrait-Maker
> was-node-suite-comfyui
> ComfyUI-LaMA-Preprocessor
> ComfyUI-Impact-Pack
> ComfyUI_node_Lilly

### Relevant console log

```Shell
No errors in console.
```

### Additional information

here is what I see

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/1736720/8fa7eb8d-904d-4bfc-8f95-6cc67245780f)

here is what everyone else sees who use my Workflow

![image](https://github.com/Gourieff/comfyui-reactor-node/assets/1736720/cd12135c-18b5-4fbe-94ae-0e4030aff5a1)

here is my Workflow as reference:

[IRL Me My Avatar v1.4.json](https://github.com/Gourieff/comfyui-reactor-node/files/14102385/IRL.Me.My.Avatar.v1.4.json)

**Comment by Gourieff** [comment]
Just try to delete the existing node from your workflow and add it again

**Comment by Gourieff** [comment]
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/08013367-f862-4540-8275-ff2c44969d70)

**Comment by Gourieff** [comment]
When I add some new fields in the node and user updates ReActor to newest version, the old node in the workflow may not be able to work any longer, this is how ComfyUI works (every workflow is just a JSON code of inputs/outputs and what modules to call with these inputs/outputs)
When I said "you should delete the node" I don't mean the folder ("the Node install directory", no need to delete it), I mean the node in the workflow
To make it work for your users (who loaded your workflow after ReActor had been updated) they just should set "face_restore_visibility" to 1 and "codeformer_weight" to 0.5 (or any other value from 0 to 1) instead of NaN, that's very simple 
When you was building your workflow you had ReActor with another version (0.4.0 or even lower), 0.4.0 doesn't have such fields as "face_restore_visibility" and "codeformer_weight" but since version 0.4.1 beta1 ReActor has these fields

I spotted about this in the instruction
![image](https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/60dd25cb-68dc-4bf4-821e-2f772d57824a)

Just re-add ReActor Node in your workflow and it will work

[IRL.Me.My.Avatar.v1.4-fixed.json](https://github.com/Gourieff/comfyui-reactor-node/files/14114740/IRL.Me.My.Avatar.v1.4-fixed.json)

**Comment by lord-lethris** [comment]
Yep - i've tried that - and i've also tried creating a new workflow.

**Comment by lord-lethris** [comment]
I tried again today - I removed the node install that did a git clone...
...This time it worked.

No idea why it didn't work before - only difference is I used ComfyUI manager the first time, then I tried a git pull, then I tried just unzipping from the repository.  This time I did a fresh git clone and it worked.

really odd.
