### ISSUE TITLE
opencv-python version breaks other plugins

### ISSUE THREAD

**Issue by BuffMcBigHuge** [Gourieff/comfyui-reactor-node#24]
Installing [comfyui-reactor-node](https://github.com/Gourieff/comfyui-reactor-node) as-is installs `opencv-python==4.8.0.76` at time of testing, which causes several breaking changes.

Modifying requirements.txt to include `opencv-python==4.7.0.72` seems to solve issues with [was-node-suite-comfyui](https://github.com/WASasquatch/was-node-suite-comfyui) and others.

**Comment by Gourieff** [comment]
You can manually install opencv-python==4.7.0.72 for the ComfyUI enclosure and this Issue will be solved:
`python_embeded\python.exe -m pip install opencv-python==4.7.0.72` from ComfyUI root

If I forcefully set opencv-python==4.7.0.72 - it also breaks different extensions, because many extensions already use opencv-python higher than 4.7.0.72 version (especially when you use ComfyUI via A1111, e.g. ControlNet uses opencv 4.8)

Newer versions of libraries are in priority, because they have different fixes and improvements
It's not my fault that some Authors still use old versions and don't want to improve their extensions code or at least test it with new versions of libs and change requirements 

<img src="https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/23086ae8-c00f-4029-8d1f-0be51ef6c297" width="50%"><img src="https://github.com/Gourieff/comfyui-reactor-node/assets/85128026/500512fb-8783-4a5f-b49f-1479a1d7cd96" width="50%">

**Comment by BuffMcBigHuge** [comment]
Thanks @Gourieff I submitted an [issue](https://github.com/WASasquatch/was-node-suite-comfyui/issues/251).
