### ISSUE TITLE
This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled

### ISSUE THREAD

**Issue by longge0126** [Gourieff/comfyui-reactor-node#273]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

 Error occurred when executing ReActorFaceSwap:

This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

### Steps to reproduce the problem

just when executing reactor-fast face swap node

### Sysinfo

windows11,4070tis

### Relevant console log

```Shell
portable comfyui
```

**Comment by q1446227740** [comment]
Error occurred when executing ReActorFaceSwap:

This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by q1446227740** [comment]
I also encountered this problem, and there was no problem yesterday.

**Comment by Gourieff** [comment]
https://github.com/Gourieff/comfyui-reactor-node/discussions/250#discussioncomment-9014289
