### ISSUE TITLE
[SOLVED] ERROR: insightface-0.7.3-cp310-cp310-win_amd64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by 2zzly** [Gourieff/comfyui-reactor-node#29]
Is it because I have an Intel CPU?
64bit windows,python 3.10.11 64bit
Followed instructions from here:
[https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild](url)
ComfyUI

*Update*
ComfyUI\python_embeded\python.exe -V is using Python 3.11.3
Could that be it?

**Comment by Gourieff** [comment]
Yes, you need Python 3.10
By default ComfyUI comes with 3.10.9 (at least that's how it was earlier), this is very strange that you have 3.11.3
I will check it tomorrow, maybe they changed the python's version recently

**Comment by Gourieff** [comment]
Or just use the prebuilt package for 3.11:
https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl

**Comment by 2zzly** [comment]
Tried:
pip install insightface-0.7.3-cp311-cp311-win_amd64.whl
Defaulting to user installation because normal site-packages is not writeable
ERROR: insightface-0.7.3-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.

**Comment by Gourieff** [comment]
> Update: This worked: python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl

Yes, this is how the instruction says

I will make a note in the readme about Python 3.11 moment
Thanks for spotting this issue

**Comment by Getafix17** [comment]
Hello, I have the same issue and I was trying to download the package for python 3.11 from https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl 
The link seems to be broken. is there some way I can download the prebuilt package for 3.11?

**Comment by schouw234** [comment]
I get this fault as well, has tried all the trouble shooting I could find :( 

Creating venv in directory D:\a1111\stable-diffusion-webui\venv using python "C:\Users\schou\AppData\Local\Programs\Python\Python310\python.exe"
venv "D:\a1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.0.1
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2619.1 MB)
Collecting torchvision==0.15.2
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting sympy
  Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting jinja2
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting filelock
  Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting networkx
  Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Collecting numpy
  Using cached numpy-1.26.3-cp310-cp310-win_amd64.whl (15.8 MB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached pillow-10.2.0-cp310-cp310-win_amd64.whl (2.6 MB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting MarkupSafe>=2.0
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Collecting mpmath>=0.19
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision
Successfully installed MarkupSafe-2.1.3 certifi-2023.11.17 charset-normalizer-3.3.2 filelock-3.13.1 idna-3.6 jinja2-3.1.2 mpmath-1.3.0 networkx-3.2.1 numpy-1.26.3 pillow-10.2.0 requests-2.31.0 sympy-1.12 torch-2.0.1+cu118 torchvision-0.15.2+cu118 typing-extensions-4.9.0 urllib3-2.1.0

[notice] A new release of pip available: 22.2.1 -> 23.3.2
[notice] To update, run: D:\a1111\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Installing clip
Installing open_clip
Installing xformers
Installing requirements for CodeFormer
Installing requirements
Collecting onnxruntime-gpu
  Using cached onnxruntime_gpu-1.16.3-cp310-cp310-win_amd64.whl (141.5 MB)
Requirement already satisfied: numpy>=1.21.6 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from onnxruntime-gpu) (1.23.5)
Requirement already satisfied: packaging in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from onnxruntime-gpu) (23.2)
Requirement already satisfied: protobuf in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from onnxruntime-gpu) (3.20.0)
Requirement already satisfied: sympy in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from onnxruntime-gpu) (1.12)
Collecting flatbuffers
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Collecting coloredlogs
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting humanfriendly>=9.1
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Requirement already satisfied: mpmath>=0.19 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from sympy->onnxruntime-gpu) (1.3.0)
Collecting pyreadline3
  Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Installing collected packages: pyreadline3, flatbuffers, humanfriendly, coloredlogs, onnxruntime-gpu
Successfully installed coloredlogs-15.0.1 flatbuffers-23.5.26 humanfriendly-10.0 onnxruntime-gpu-1.16.3 pyreadline3-3.4.1
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: Pillow in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (9.5.0)
Requirement already satisfied: matplotlib in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (3.8.2)
Collecting easydict
  Using cached easydict-1.11.tar.gz (6.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: requests in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (2.31.0)
Requirement already satisfied: scikit-image in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (0.21.0)
Collecting cython
  Using cached Cython-3.0.7-cp310-cp310-win_amd64.whl (2.8 MB)
Collecting onnx
  Using cached onnx-1.15.0-cp310-cp310-win_amd64.whl (14.3 MB)
Requirement already satisfied: tqdm in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (4.66.1)
Collecting prettytable
  Using cached prettytable-3.9.0-py3-none-any.whl (27 kB)
Requirement already satisfied: scipy in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.11.4)
Collecting scikit-learn
  Using cached scikit_learn-1.3.2-cp310-cp310-win_amd64.whl (9.3 MB)
Collecting albumentations
  Using cached albumentations-1.3.1-py3-none-any.whl (125 kB)
Requirement already satisfied: numpy in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.23.5)
Collecting qudida>=0.0.4
  Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
Collecting opencv-python-headless>=4.1.1
  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
Requirement already satisfied: PyYAML in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
Requirement already satisfied: imageio>=2.27 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2.33.1)
Requirement already satisfied: tifffile>=2022.8.12 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2023.12.9)
Requirement already satisfied: networkx>=2.8 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (3.2.1)
Requirement already satisfied: packaging>=21 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (23.2)
Requirement already satisfied: lazy_loader>=0.2 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (0.3)
Requirement already satisfied: PyWavelets>=1.1.1 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (1.5.0)
Requirement already satisfied: cycler>=0.10 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (4.47.0)
Requirement already satisfied: contourpy>=1.0.1 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
Requirement already satisfied: python-dateutil>=2.7 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (2.8.2)
Collecting protobuf>=3.20.2
  Using cached protobuf-4.25.1-cp310-abi3-win_amd64.whl (413 kB)
Requirement already satisfied: wcwidth in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.13)
Requirement already satisfied: certifi>=2017.4.17 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2023.11.17)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Collecting joblib>=1.1.1
  Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Requirement already satisfied: colorama in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: six>=1.5 in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
Requirement already satisfied: typing-extensions in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from qudida>=0.0.4->albumentations->insightface==0.7.3) (4.9.0)
Using legacy 'setup.py install' for easydict, since package 'wheel' is not installed.
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml): started
  Building wheel for insightface (pyproject.toml): finished with status 'error'
Failed to build insightface
Collecting onnx>=1.14.0
  Using cached onnx-1.15.0-cp310-cp310-win_amd64.whl (14.3 MB)
Collecting protobuf>=3.20.2
  Using cached protobuf-4.25.1-cp310-abi3-win_amd64.whl (413 kB)
Requirement already satisfied: numpy in d:\a1111\stable-diffusion-webui\venv\lib\site-packages (from onnx>=1.14.0) (1.23.5)
Installing collected packages: protobuf, onnx
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.0
    Uninstalling protobuf-3.20.0:
      Successfully uninstalled protobuf-3.20.0
Successfully installed onnx-1.15.0 protobuf-4.25.1
Error: The 'onnxruntime-gpu' distribution was not found and is required by the application
Error: The 'insightface==0.7.3' distribution was not found and is required by the application
Error: The 'onnx>=1.14.0' distribution was not found and is required by the application

        +---------------------------------+
        --- PLEASE, RESTART the Server! ---
        +---------------------------------+
Launching Web UI with arguments: --xformers --autolaunch
Style database not found: D:\a1111\stable-diffusion-webui\styles.csv
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "D:\a1111\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\a1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "D:\a1111\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\a1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\a1111\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\a1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 18, in <module>
        from reactor_ui import ui_main, ui_upscale, ui_tools, ui_settings
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\reactor_ui\__init__.py", line 2, in <module>
        import reactor_ui.reactor_tools_ui as ui_tools
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\reactor_ui\reactor_tools_ui.py", line 2, in <module>
        from scripts.reactor_swapper import build_face_model
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_helpers.py
    Traceback (most recent call last):
      File "D:\a1111\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\a1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_logger.py
    Traceback (most recent call last):
      File "D:\a1111\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\a1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in <module>
        from scripts.reactor_helpers import addLoggingLevel
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "D:\a1111\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\a1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_version.py
    Traceback (most recent call last):
      File "D:\a1111\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\a1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_version.py", line 4, in <module>
        from scripts.reactor_logger import logger, get_Run, set_Run
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in <module>
        from scripts.reactor_helpers import addLoggingLevel
      File "D:\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
Loading weights [6ce0161689] from D:\a1111\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: D:\a1111\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 530.1s (prepare environment: 508.2s, launcher: 0.1s, import torch: 6.7s, import gradio: 2.4s, setup paths: 2.9s, initialize shared: 0.5s, other imports: 2.0s, setup codeformer: 0.2s, load scripts: 1.5s, initialize extra networks: 0.9s, create ui: 3.4s, gradio launch: 1.3s).
Applying attention optimization: xformers... done.
Model loaded in 85.9s (load weights from disk: 4.0s, create model: 0.7s, apply weights to model: 80.1s, apply half(): 0.3s, load VAE: 0.1s, calculate empty prompt: 0.6s).

**Comment by xuewuzhijin** [comment]
困扰我几天的问题，解决了。
`E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded>python.exe -V`
`>>>Python 3.11.8`
`E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded>python.exe -m pip install https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl`

如果直接使用  `pip install ...cp311-win_amd64.whl` 他是无效的，必须要在 `python_embeded` 路径下执行命令，如果Comfyui内的Python是3.10的版本，那么就安装 ...cp311-win_amd64.whl 就行。

**Comment by Vektor369** [comment]
> 困扰我几天的问题，解决了。 `E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded>python.exe -V` `>>>Python 3.11.8` `E:\Stable Diffusion\ComfyUI_windows_portable\python_embeded>python.exe -m pip install https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl`
> 
> 如果直接使用 `pip install ...cp311-win_amd64.whl` 他是无效的，必须要在 `python_embeded` 路径下执行命令，如果Comfyui内的Python是3.10的版本，那么就安装 ...cp311-win_amd64.whl 就行。

天哪！谢谢！！！

**Comment by KrissOk1** [comment]
Hiya, just created an account to share my solve in Krita (local managed server). I know pretty much nothing about coding, but solution I found :)
Seems the latest Krita Ai python script directs to download the latest release of Python, which installs Python 3.11.9 (right now, 16th of sept. 2024). Conflict ensues because Krita is then set to install the 310 version of the IP-Adapter rather than the 311.

Ok, probleme, so, then point Krita to install the compatible 311 version of the IP-adapter, m'kay?

What to do:
Unzip the downloaded script file (the one intended to be run from 'tools' in Krita. At the time of writing it is 'krita_ai_diffusion-1.24.0.zip'. One file ("ai-diffusion.desktop") and one folder will be extracted. In the folder 'ai_diffusion', open the file 'server.py' in a text editor. Find the line "_install_insightface". A couple of lines down it says   "whl_file = self._cache_dir / "insightface-0.7.3-cp310-cp310-win_amd64.whl", Change the 310 to 311.
Beneath that is the URL it gets the file from. I changed to the URL I've currently got for the file, so that line is:
whl_url = "https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl"

Save the file.

Now make a zip file with the folder "ai-diffusion" and the file "ai_diffusion.desktop", you can name it whatever. Start, or restart, Krita, go to tools > scripts > 'import python plugin from file', and choose the zip you just made. Click 'ok' when asked to overwrite (or whatever the prompts was).
Restart Krita. Open new file.
Then open the AI-image docker > configuration > 'Connection' and check the 'IP-Adapters' > press install. Presto!

Trying to write so fellow n00bs like myself can follow.

(btw, I tried several other tips, of which I could get none working with local server in Krita)

**Comment by mskyan** [comment]
> Hiya, just created an account to share my solve in Krita (local managed server). I know pretty much nothing about coding, but solution I found :) Seems the latest Krita Ai python script directs to download the latest release of Python, which installs Python 3.11.9 (right now, 16th of sept. 2024). Conflict ensues because Krita is then set to install the 310 version of the IP-Adapter rather than the 311.
> 
> Ok, probleme, so, then point Krita to install the compatible 311 version of the IP-adapter, m'kay?
> 
> What to do: Unzip the downloaded script file (the one intended to be run from 'tools' in Krita. At the time of writing it is 'krita_ai_diffusion-1.24.0.zip'. One file ("ai-diffusion.desktop") and one folder will be extracted. In the folder 'ai_diffusion', open the file 'server.py' in a text editor. Find the line "_install_insightface". A couple of lines down it says "whl_file = self._cache_dir / "insightface-0.7.3-cp310-cp310-win_amd64.whl", Change the 310 to 311. Beneath that is the URL it gets the file from. I changed to the URL I've currently got for the file, so that line is: whl_url = "https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl"
> 
> Save the file.
> 
> Now make a zip file with the folder "ai-diffusion" and the file "ai_diffusion.desktop", you can name it whatever. Start, or restart, Krita, go to tools > scripts > 'import python plugin from file', and choose the zip you just made. Click 'ok' when asked to overwrite (or whatever the prompts was). Restart Krita. Open new file. Then open the AI-image docker > configuration > 'Connection' and check the 'IP-Adapters' > press install. Presto!
> 
> Trying to write so fellow n00bs like myself can follow.
> 
> (btw, I tried several other tips, of which I could get none working with local server in Krita)

Thank you so much! By you, I could solve the issue in 30 minutes from the start web searching!

For ALREADY INSTALLED ai_diffusion users, your target 'server.py' file is located at (your resource foldter)\pykrita\ai_diffusion\server.py
(i.e. K:\Apps\Krita (x64)\resource\pykrita\ai_diffusion\server.py)
(Maybe, before the editing, backup copying is recommended.)
And follow the @KrissOk1 's instructions.

**Comment by KrissOk1** [comment]
> > Hiya, just created an account to share my solve in Krita (local managed server). I know pretty much nothing about coding, but solution I found :) Seems the latest Krita Ai python script directs to download the latest release of Python, which installs Python 3.11.9 (right now, 16th of sept. 2024). Conflict ensues because Krita is then set to install the 310 version of the IP-Adapter rather than the 311.
> > Ok, probleme, so, then point Krita to install the compatible 311 version of the IP-adapter, m'kay?
> > What to do: Unzip the downloaded script file (the one intended to be run from 'tools' in Krita. At the time of writing it is 'krita_ai_diffusion-1.24.0.zip'. One file ("ai-diffusion.desktop") and one folder will be extracted. In the folder 'ai_diffusion', open the file 'server.py' in a text editor. Find the line "_install_insightface". A couple of lines down it says "whl_file = self._cache_dir / "insightface-0.7.3-cp310-cp310-win_amd64.whl", Change the 310 to 311. Beneath that is the URL it gets the file from. I changed to the URL I've currently got for the file, so that line is: whl_url = "https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl"
> > Save the file.
> > Now make a zip file with the folder "ai-diffusion" and the file "ai_diffusion.desktop", you can name it whatever. Start, or restart, Krita, go to tools > scripts > 'import python plugin from file', and choose the zip you just made. Click 'ok' when asked to overwrite (or whatever the prompts was). Restart Krita. Open new file. Then open the AI-image docker > configuration > 'Connection' and check the 'IP-Adapters' > press install. Presto!
> > Trying to write so fellow n00bs like myself can follow.
> > (btw, I tried several other tips, of which I could get none working with local server in Krita)
> 
> Thank you so much! By you, I could solve the issue in 30 minutes from the start web searching!
> 
> For ALREADY INSTALLED ai_diffusion users, your target 'server.py' file is located at (your resource foldter)\pykrita\ai_diffusion\server.py (i.e. K:\Apps\Krita (x64)\resource\pykrita\ai_diffusion\server.py) (Maybe, before the editing, backup copying is recommended.) And follow the @KrissOk1 's instructions.

Happy to hear that! Since I didn't understand acly's post above, I spent probably 4-5h trying everything I found on the internet, until I deduced that this might be the solution and then started going through file by file searching for "insightface" and something that  directs which version to download and from where.
Thanks for your clarifying contribution, I'm sure it'll be handy for those of us who aren't as savvy as the average github peruser seem to be :)
