### ISSUE TITLE
error:This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']

### ISSUE THREAD

**Issue by whmc76** [Gourieff/comfyui-reactor-node#54]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

![7b8296f2898863fdbfe3fae4c86da209](https://github.com/Gourieff/comfyui-reactor-node/assets/129386342/09eac17e-ce8b-4da8-ae12-39e3443aebeb)

### Steps to reproduce the problem

Your workflow
run with reactor node,

### Sysinfo

in the image

### Relevant console log

```Shell
in the image
```

### Additional information

this issue should be the same https://github.com/Gourieff/sd-webui-reactor/issues/105
pls help fix it ,thx

**Comment by Gourieff** [comment]
https://github.com/Gourieff/comfyui-reactor-node/issues/41

**Comment by zba** [comment]
just fall into this issue, so onnxruntime-gpu not supported at all ? isn't it better to fix it instead of asking to use cpu version ?

**Comment by Gourieff** [comment]
Fix it? Is it broken?
Asking to use? It's a free extension that I develop with enthusiasm in my free time. If you don't like it, you can make your own or use any other - what's the problem?
ReActor Node uses ORT because **ORT-GPU won't work with Intel/AMD GPUs and Mac M1/M2**
ORT is universal for **any** platfrom, ORT-GPU is not.
I have in plans to make a separate node for nvidia GPUs with ort-gpu support soon when I have free time and aspiration for this.
